Update bin/remakerings to suport custom swift_dir
SWIFT_ROOT will be looked up in the environment variables and used
if set

diff --git a/doc/saio/bin/remakerings b/doc/saio/bin/remakerings
--- a/doc/saio/bin/remakerings
+++ b/doc/saio/bin/remakerings
@@ -1,6 +1,21 @@
 #!/bin/bash
 
-cd /etc/swift
+if [ -z "${SWIFT_ROOT}" ]; then
+    echo "Setting SWIFT_ROOT"
+    export SWIFT_ROOT='/etc/swift'
+fi
+
+if [ ! -d ${SWIFT_ROOT} ]; then
+    echo "Error: '${SWIFT_ROOT}' not a valid directory"
+    exit 1
+fi
+
+if [ ! -w ${SWIFT_ROOT} ]; then
+    echo "Error: ${SWIFT_ROOT} not writable"
+    exit 1
+fi
+
+cd ${SWIFT_ROOT}
 
 rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz
 
@@ -38,3 +53,4 @@ swift-ring-builder account.builder add r1z2-127.0.0.1:6022/sdb2 1
 swift-ring-builder account.builder add r1z3-127.0.0.1:6032/sdb3 1
 swift-ring-builder account.builder add r1z4-127.0.0.1:6042/sdb4 1
 swift-ring-builder account.builder rebalance
+~
