Update bin/remakerings to suport custom swift_dir
SWIFT_ROOT will be looked up in the environment variables and used
if set

diff --git a/doc/saio/bin/remakerings b/doc/saio/bin/remakerings
--- a/doc/saio/bin/remakerings
+++ b/doc/saio/bin/remakerings
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 <<<<<<< HEAD
+<<<<<<< HEAD
 if [ -z "${SWIFT_ROOT}" ]; then
     echo "Setting SWIFT_ROOT"
     export SWIFT_ROOT='/etc/swift'
@@ -22,6 +23,29 @@ set -e
 
 cd /etc/swift
 >>>>>>> Apply bash error handling consistently in all bash scripts
+=======
+set -e
+
+cd /etc/swift
+=======
+if [ -z "${SWIFT_ROOT}" ]; then
+    echo "Setting SWIFT_ROOT"
+    export SWIFT_ROOT='/etc/swift'
+fi
+
+if [ ! -d ${SWIFT_ROOT} ]; then
+    echo "Error: '${SWIFT_ROOT}' not a valid directory"
+    exit 1
+fi
+
+if [ ! -w ${SWIFT_ROOT} ]; then
+    echo "Error: ${SWIFT_ROOT} not writable"
+    exit 1
+fi
+
+cd ${SWIFT_ROOT}
+>>>>>>> Update bin/remakerings to suport custom swift_dir
+>>>>>>> Update bin/remakerings to suport custom swift_dir
 
 rm -f *.builder *.ring.gz backups/*.builder backups/*.ring.gz
 
